name: Luacheck
on: push
jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
